// Generated by CoffeeScript 1.4.0

window.log = function() {
  log.history = log.history || [];
  log.history.push(arguments);
  if (this.console) {
    console.log(Array.prototype.slice.call(arguments));
  }
};

require(['settings', 'renderer'], function(settings, renderer) {});
