// Generated by CoffeeScript 1.4.0

window.log = function() {
  log.history = log.history || [];
  log.history.push(arguments);
  if (this.console) {
    console.log(Array.prototype.slice.call(arguments));
  }
};

require(['settings', 'render/render', 'state/State', 'environ/Commands', 'environ/browser', 'level/level01'], function(settings, render, State, Commands, browser, level01) {
  var canvas, commands, ctx, gameLoopId, state, _ref;
  canvas = browser.getCanvas('gameScreen');
  _ref = [canvas.getContext('2d'), canvas.width, canvas.height], ctx = _ref[0], settings.screen.width = _ref[1], settings.screen.height = _ref[2];
  commands = new Commands(settings);
  browser.bindCommands(commands);
  state = new State(settings);
  state.startLevel(level01);
  gameLoopId = setInterval(function() {
    if (commands.quitCommand()) {
      clearInterval(gameLoopId);
    }
    if (state.condition === 'crashed') {
      clearInterval(gameLoopId);
    }
    state.update(commands);
    return render(ctx, settings, state);
  }, 1000 / settings.screen.framesPerSecond);
});
