// Generated by CoffeeScript 1.4.0

define(function() {
  var BaseState;
  return BaseState = (function() {

    function BaseState(settings) {
      this.settings = settings;
      this.positionX = 0;
      this.positionY = 0;
    }

    return BaseState;

  })();
});
