// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['baseShape', 'Translator', 'collisionDetect'], function(baseShape, Translator, collisionDetect) {
  var BaseState;
  return BaseState = (function() {

    function BaseState(settings) {
      this.settings = settings;
      this.externalBoxPoints = __bind(this.externalBoxPoints, this);

      this.livePoints = __bind(this.livePoints, this);

      this.position = [0, 0];
    }

    BaseState.prototype.livePoints = function() {
      var point, translator, _i, _len, _ref, _results;
      translator = new Translator;
      _ref = baseShape.points;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        point = _ref[_i];
        _results.push(translator.translate(point, this.position));
      }
      return _results;
    };

    BaseState.prototype.externalBoxPoints = function() {
      return collisionDetect.externalLimits(this.livePoints());
    };

    return BaseState;

  })();
});
