// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(function() {
  var Commands;
  return Commands = (function() {

    function Commands(settings) {
      this.settings = settings;
      this._generalHandler = __bind(this._generalHandler, this);

      this.keyUpHandler = __bind(this.keyUpHandler, this);

      this.keyDownHandler = __bind(this.keyDownHandler, this);

      this.quitCommand = __bind(this.quitCommand, this);

      this.currentThrustCommand = __bind(this.currentThrustCommand, this);

      this.currentTurnCommand = __bind(this.currentTurnCommand, this);

      this.commands = {
        left: false,
        right: false,
        thrust: false,
        stop: false
      };
    }

    Commands.prototype.currentTurnCommand = function() {
      if (this.commands.right && !this.commands.left) {
        return this.settings.ship.turnRatio;
      }
      if (this.commands.left && !this.commands.right) {
        return -1 * this.settings.ship.turnRatio;
      }
      return 0;
    };

    Commands.prototype.currentThrustCommand = function() {
      return this.commands.thrust;
    };

    Commands.prototype.quitCommand = function() {
      return this.commands.stop;
    };

    Commands.prototype.keyDownHandler = function(e) {
      return this._generalHandler(e, true);
    };

    Commands.prototype.keyUpHandler = function(e) {
      return this._generalHandler(e, false);
    };

    Commands.prototype._generalHandler = function(e, sense) {
      var command, keyId;
      keyId = e[e.charCode ? 'charCode' : 'keyCode'];
      command = this.settings.game.keyCommandMap[keyId];
      if (command != null) {
        return this.commands[command] = sense;
      }
    };

    return Commands;

  })();
});
