// Generated by CoffeeScript 1.4.0

define(function() {
  var ExhaustState;
  return ExhaustState = (function() {

    function ExhaustState(settings) {
      var puffs;
      this.settings = settings;
      puffs = [];
    }

    ExhaustState.prototype.update = function() {};

    return ExhaustState;

  })();
});
