// Generated by CoffeeScript 1.4.0

define({
  acceleration: function(mass, force) {
    return force / mass;
  },
  energy: function(mass, velocity) {
    return 0.5 * mass * velocity * velocity;
  }
});
