// Generated by CoffeeScript 1.4.0
var physics;

physics = {
  acceleration: function(mass, force) {
    return force / mass;
  },
  energy: function(mass, velocity) {
    return 0.5 * mass * velocity * velocity;
  }
};

exports.physics = physics;
