// Generated by CoffeeScript 1.4.0

define(['./rendererBackground', './rendererShip'], function(rendererBackground, rendererShip) {
  return function(ctx, settings, state) {
    rendererBackground(ctx, settings);
    rendererShip(ctx, settings, state);
  };
});
