// Generated by CoffeeScript 1.4.0

define(function() {
  return function(ctx, settings) {
    ctx.fillStyle = settings.background.color;
    ctx.fillRect(0, 0, settings.screen.width, settings.screen.height);
    log(settings.height);
  };
});
