// Generated by CoffeeScript 1.4.0

define(function() {
  return function(ctx, settings, state) {
    var puff, _i, _len, _ref;
    ctx.save();
    ctx.fillStyle = settings.ship.exhaust.color;
    _ref = state.exhaust.puffs;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      puff = _ref[_i];
      ctx.fillRect(puff[1] - 1, puff[2] - 1, 2, 2);
    }
    ctx.restore();
  };
});
