// Generated by CoffeeScript 1.4.0

define(['rendererBackground', 'rendererShip', 'rendererExhaust', 'rendererBullet', 'rendererBase'], function(rendererBackground, rendererShip, rendererExhaust, rendererBullet, rendererBase) {
  return function(ctx, settings, state) {
    rendererBackground(ctx, settings, state);
    rendererExhaust(ctx, settings, state);
    rendererBullet(ctx, settings, state);
    rendererShip(ctx, settings, state);
    rendererBase(ctx, settings, state);
    ctx.translate(-state.screenState.nextShiftX, -state.screenState.nextShiftY);
  };
});
