// Generated by CoffeeScript 1.4.0

define(function() {
  return function(ctx, settings, state) {
    var point, pointSet, _i, _len;
    ctx.save();
    ctx.translate(state.baseState.positionX, state.baseState.positionY);
    ctx.fillStyle = settings.base.color;
    pointSet = state.baseState.livePoints();
    log(pointSet);
    ctx.beginPath();
    ctx.moveTo(pointSet[0][0], pointSet[0][1]);
    for (_i = 0, _len = pointSet.length; _i < _len; _i++) {
      point = pointSet[_i];
      ctx.lineTo(point[0], point[1]);
    }
    ctx.closePath();
    ctx.stroke();
    ctx.fill();
    ctx.restore();
  };
});
