// Generated by CoffeeScript 1.4.0

define(['./shipShape'], function(shipShape) {
  return function(ctx, settings, state) {
    var nose, point, startX, startY, _i, _len, _ref, _ref1;
    _ref = [state.shipState.x, state.shipState.y], startX = _ref[0], startY = _ref[1];
    ctx.save();
    ctx.strokeStyle = settings.ship.color;
    ctx.fillStyle = 'red';
    ctx.translate(startX, startY);
    ctx.fillRect(-1, -1, 2, 2);
    ctx.rotate(45 * Math.PI / 180);
    nose = shipShape.points[0];
    ctx.moveTo(nose[0], nose[1]);
    ctx.beginPath();
    _ref1 = shipShape.points;
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      point = _ref1[_i];
      ctx.lineTo(point[0], point[1]);
    }
    ctx.lineTo(nose[0], nose[1]);
    ctx.stroke();
    ctx.translate(0, 0);
    ctx.restore();
  };
});
