// Generated by CoffeeScript 1.4.0

define(function() {
  /*
  		In our world, as we are looking at the canvas, 
  		(x, y) = (0,0) is the top-left of the canvas, so...
  
  		-	x increases as we move right
  		-	y increases as we move down
  		-	rads the clockwise angle is from the upward vertical
  */
  return function(x, y, rads) {
    return [Math.cos(-rads) * x + Math.sin(-rads) * y, -Math.sin(-rads) * x + Math.cos(-rads) * y];
  };
});
