// Generated by CoffeeScript 1.4.0

define(function() {
  var ScreenState;
  return ScreenState = (function() {

    function ScreenState(settings) {
      this.settings = settings;
      this.positionX = 0;
      this.positionY = 0;
      this.nextShiftX = 0;
      this.nextShiftY = 0;
    }

    ScreenState.prototype.update = function(shipState) {
      var strayBottomAmount, strayBottomThreshold, strayLeftAmount, strayLeftThreshold, strayRightAmount, strayRightThreshold, strayTopAmount, strayTopThreshold;
      this.nextShiftX = 0;
      this.nextShiftY = 0;
      strayRightThreshold = this.positionX + this.settings.screen.width - this.settings.screen.panWhenWithin;
      strayRightAmount = shipState.positionX - strayRightThreshold;
      if (strayRightAmount > 0 && this.positionX < (this.settings.game.width - this.settings.screen.width)) {
        this.nextShiftX = strayRightAmount;
        this.positionX += this.nextShiftX;
      } else {
        strayLeftThreshold = this.positionX + this.settings.screen.panWhenWithin;
        strayLeftAmount = strayLeftThreshold - shipState.positionX;
        if (strayLeftAmount > 0 && this.positionX > 0) {
          this.nextShiftX = -strayLeftAmount;
          this.positionX += this.nextShiftX;
        }
      }
      strayBottomThreshold = this.positionY + this.settings.screen.height - this.settings.screen.panWhenWithin;
      strayBottomAmount = shipState.positionY - strayBottomThreshold;
      if (strayBottomAmount > 0 && this.positionY < (this.settings.game.height - this.settings.screen.height)) {
        this.nextShiftY = strayBottomAmount;
        return this.positionY += this.nextShiftY;
      } else {
        strayTopThreshold = this.positionY + this.settings.screen.panWhenWithin;
        strayTopAmount = strayTopThreshold - shipState.positionY;
        if (strayTopAmount > 0 && this.positionY > 0) {
          this.nextShiftY = -strayTopAmount;
          return this.positionY += this.nextShiftY;
        }
      }
    };

    return ScreenState;

  })();
});
