// Generated by CoffeeScript 1.4.0

define(function() {
  var ScreenState;
  return ScreenState = (function() {

    function ScreenState(settings) {
      this.settings = settings;
      this.position = [0, 0];
      this.nextShiftX = 0;
      this.nextShiftY = 0;
    }

    ScreenState.prototype.update = function(shipState) {
      var strayBottomAmount, strayBottomThreshold, strayLeftAmount, strayLeftThreshold, strayRightAmount, strayRightThreshold, strayTopAmount, strayTopThreshold;
      this.nextShiftX = 0;
      this.nextShiftY = 0;
      strayRightThreshold = this.position[0] + this.settings.screen.width - this.settings.screen.panWhenWithin;
      strayRightAmount = shipState.position[0] - strayRightThreshold;
      if (strayRightAmount > 0 && this.position[0] < (this.settings.game.width - this.settings.screen.width)) {
        this.nextShiftX = strayRightAmount;
        this.position[0] += this.nextShiftX;
      } else {
        strayLeftThreshold = this.position[0] + this.settings.screen.panWhenWithin;
        strayLeftAmount = strayLeftThreshold - shipState.position[0];
        if (strayLeftAmount > 0 && this.position[0] > 0) {
          this.nextShiftX = -strayLeftAmount;
          this.position[0] += this.nextShiftX;
        }
      }
      strayBottomThreshold = this.position[1] + this.settings.screen.height - this.settings.screen.panWhenWithin;
      strayBottomAmount = shipState.position[1] - strayBottomThreshold;
      if (strayBottomAmount > 0 && this.position[1] < (this.settings.game.height - this.settings.screen.height)) {
        this.nextShiftY = strayBottomAmount;
        return this.position[1] += this.nextShiftY;
      } else {
        strayTopThreshold = this.position[1] + this.settings.screen.panWhenWithin;
        strayTopAmount = strayTopThreshold - shipState.position[1];
        if (strayTopAmount > 0 && this.position[1] > 0) {
          this.nextShiftY = -strayTopAmount;
          return this.position[1] += this.nextShiftY;
        }
      }
    };

    return ScreenState;

  })();
});
