// Generated by CoffeeScript 1.4.0
var getIp, http, server, sys;

sys = require("sys");

http = require("http");

getIp = function(req) {
  if (req.headers['x-forwarded-for']) {
    return req.headers['x-forwarded-for'];
  } else {
    return req.connection.remoteAddress;
  }
};

server = http.createServer(function(request, response) {
  response.writeHead(200, {
    "content-type": "text/plain"
  });
  response.write("Hello world\n");
  response.write(getIp(request));
  response.end();
});

server.listen(8080);

sys.puts("Server is running on 8080");
