// Generated by CoffeeScript 1.4.0

define({
  background: {
    height: 10,
    width: 5,
    color: '#eeeeee'
  },
  ship: {
    color: '#999999',
    thrustRatio: 1,
    turnRatio: 1
  },
  screen: {
    height: 0,
    width: 0
  }
});
