// Generated by CoffeeScript 1.4.0

define({
  background: {
    color: '#eeeeee'
  },
  ship: {
    color: '#999999',
    thrustRatio: 1,
    turnRatio: 10
  },
  screen: {
    height: 0,
    width: 0,
    framesPerSecond: 30,
    leftButtonCode: 37,
    rightButtonCode: 39
  }
});
