// Generated by CoffeeScript 1.4.0

define(['./physics'], function(physics) {
  var ShipState;
  return ShipState = (function() {

    function ShipState(settings) {
      this.velocity = 0;
      this.direction = 0;
      this.x = 0;
      this.y = 0;
      this.thrust = settings.ship.thrust;
    }

    ShipState.prototype.go = function() {};

    return ShipState;

  })();
});
