// Generated by CoffeeScript 1.4.0

define(['./shipState', './StateKey'], function(ShipState, StateKey) {
  var State;
  return State = (function() {

    function State(settings) {
      this.shipState = new ShipState(settings);
      this.keyState = new StateKey(settings);
    }

    State.prototype.update = function() {
      this.shipState.changeDirection(this.keyState.currentCommand());
    };

    return State;

  })();
});
