// Generated by CoffeeScript 1.4.0

define(function() {
  return {
    rotate: function(x, y, rads) {
      return [Math.cos(-rads) * x + Math.sin(-rads) * y, -Math.sin(-rads) * x + Math.cos(-rads) * y];
    },
    translate: function(point, coordinates) {
      return [point[0] + coordinates[0], point[1] + coordinates[1]];
    }
  };
});
