// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(function() {
  var Translator;
  return Translator = (function() {

    function Translator() {
      this.translatePoints = __bind(this.translatePoints, this);

      this.translate = __bind(this.translate, this);

    }

    Translator.prototype.rotate = function(x, y, rads) {
      return [Math.cos(-rads) * x + Math.sin(-rads) * y, -Math.sin(-rads) * x + Math.cos(-rads) * y];
    };

    Translator.prototype.translate = function(point, coordinates) {
      return [point[0] + coordinates[0], point[1] + coordinates[1]];
    };

    Translator.prototype.translatePoints = function(points, coordinates) {
      var point, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = points.length; _i < _len; _i++) {
        point = points[_i];
        _results.push(this.translate(point, coordinates));
      }
      return _results;
    };

    return Translator;

  })();
});
