// Generated by CoffeeScript 1.4.0

define(['../js/rotationTranslator'], function(rotationTranslator) {
  return describe("The translator", function() {
    return it("should return the string", function() {
      return expect(rotationTranslator(".")).toEqual("..");
    });
  });
});
