// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['shape/baseShape', 'logic/Translator'], function(baseShape, Translator) {
  var BaseState;
  return BaseState = (function() {

    function BaseState(settings) {
      this.settings = settings;
      this.externalBoxPoints = __bind(this.externalBoxPoints, this);

      this.livePoints = __bind(this.livePoints, this);

      this.position = [0, 0];
      this.translator = new Translator;
    }

    BaseState.prototype.livePoints = function() {
      var point, _i, _len, _ref, _results;
      _ref = baseShape.points;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        point = _ref[_i];
        _results.push(this.translator.translate(point, this.position));
      }
      return _results;
    };

    BaseState.prototype.externalBoxPoints = function() {
      return this.translator.externalLimits(this.livePoints());
    };

    return BaseState;

  })();
});
