// Generated by CoffeeScript 1.4.0

define(['render/renderBackground', 'render/renderShip', 'render/renderExhaust', 'render/renderBullet', 'render/renderBase'], function(renderBackground, renderShip, renderExhaust, renderBullet, renderBase) {
  return function(ctx, settings, state) {
    renderBackground(ctx, settings, state);
    renderExhaust(ctx, settings, state);
    renderBullet(ctx, settings, state);
    renderShip(ctx, settings, state);
    renderBase(ctx, settings, state);
    ctx.translate(-state.screenState.nextShiftX, -state.screenState.nextShiftY);
  };
});
